## this is my first .ipynb

In [28]:
from turtledemo.penrose import start

import numpy as np
a = np.array(1)
print(a, a.shape)

1 ()


In [29]:
a = np.array([1,2])
print(a, a.shape)

[1] (1,)


In [33]:
a = np.array([[1,2,3], [4,5,6]])
print(a, a.shape,a.dtype)

[[1 2 3]
 [4 5 6]] (2, 3) int64


# np.empty will generate random numbers just to fill the space

In [42]:
b = np.empty((3,4,4))
print(b, b.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] (3, 4, 4)


# arange function used to create an 1D array with entries [s,e)

In [45]:
c = np.arange(5)
print(c, c.shape)

[0 1 2 3 4] (5,)


# use arange and reshape to form entries with entries 1 to 9

In [126]:
M = np.arange(0, 12).reshape(3, 4)
print(M, M.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [48]:
d = np.linspace(0,10,5)# END is included
g = np.linspace(0, 10, 5, dtype=int)
print(d, d.shape)
print(g, g.shape)

[0. 2. 4. 6. 8.] (5,)
[ 0.   2.5  5.   7.5 10. ] (5,)


In [49]:
f = np.logspace(0,6,3,base=2)# the number are the index of base
print(f, f.shape)

[ 1.  8. 64.] (3,)


Generate matrix whose main diagonal is 1

In [51]:
g = np.eye(3,4)

print(g, g.shape)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] (3, 4)


# generate n*n matrix whose main diagonal is the number in the input list

In [54]:
h = np.diag([1,2,3,4,5.])
print(h, h.shape)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]] (5, 5)


# generate random numbers to fill the matrix between 0 - 1 dtype float

In [55]:
i = np.random.rand(3,2)
print(i, i.shape)

[[0.47324427 0.17583632]
 [0.22088977 0.57946166]
 [0.38249404 0.60883833]] (3, 2)


# generate random floats between specified range

In [57]:
j = np.random.uniform(3,7,size=(3,3))
print(j, j.shape)

[[3.97899417 3.84085483 6.25987096]
 [4.72697848 3.39403982 4.63388384]
 [3.95355518 5.82589282 5.22744648]] (3, 3)


# generate random int in specified range [a,b)#

In [122]:
k = np.random.randint(3,7,size=(3,3))
print(k, k.shape)

[[3 6 6]
 [6 3 5]
 [4 5 4]] (3, 3)


In [117]:
# generate floats based on normal distribution with mean and variance equal to 0 and 1

In [118]:
l = np.random.randn(3,3)
print(l, l.shape)

[[ 1.01050418 -0.27775188 -1.76484209]
 [-1.27507077 -1.22198204 -1.87963085]
 [-0.33998637 -0.12556068 -0.27696472]] (3, 3)


[[84  8 39]
 [38 98 19]
 [27 82 25]
 [77  4 75]] (4, 3)
[[np.int64(84), np.int64(38), np.int64(27), np.int64(77)], [np.int64(8), np.int64(98), np.int64(82), np.int64(4)], [np.int64(39), np.int64(19), np.int64(25), np.int64(75)]]


In [115]:
print(a[[1, 2], 1:])
print(a[:, 0][a[:, 0] > 27])

[[98 19]
 [82 25]]
[84 38 77]


In [109]:
print(a[1, (a[1] > 50) & (a[1] < 90)])
print(a[1] > 20)
print(a[::2])  # slicing is also supported in numpy

[82]
[ True  True False]
[[63 23 32]
 [72 66 67]]


In [127]:
a = np.arange(9).reshape(3,3)
print(a.transpose().tolist())

[[0, 3, 6], [1, 4, 7], [2, 5, 8]]
