## this is my first .ipynb

In [1]:
print('hello vscode')

hello vscode


In [2]:
import numpy as np
import random
a = np.array([[0 for _ in range(3)] for _ in range(3)])
a += random.randint(1,10)
print(a)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
