In [1]:
from inspect import stack

import numpy as np

In [3]:
a = np.random.randint(1,100,size=(2,5,5))
print(a, a.shape)

[[[23 76 91 17 78]
  [68 47 15 97 44]
  [67 81 44 87 70]
  [20 78 48 94 37]
  [91 47 23 68 86]]

 [[27 91 94  5 19]
  [24 54 40 54 80]
  [20 96 66 17 10]
  [ 4 75 55 16 88]
  [17 46 83 69 24]]] (2, 5, 5)


In [5]:
print(a[0,3:5,3:5])

[[47 64]
 [85 34]]


In [4]:
print(a[0].diagonal())

[23 47 44 94 86]


In [8]:
print(np.zeros((3,3),dtype = 'bool'))

[[False False False]
 [False False False]
 [False False False]]


In [3]:
temp = np.random.randint(26,40,(10,))
print(temp)

[31 38 39 29 27 26 39 31 33 27]


In [11]:
print('{:.3f}'.format(np.mean(temp)))
print(np.where(temp > 30, True,[bool(0) for _ in range(10)]))

32.000
[ True  True  True False False False  True  True  True False]


In [17]:
a = np.ones((3,3))
print(a,np.cumsum(a),np.cumsum(a).shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [1. 2. 3. 4. 5. 6. 7. 8. 9.] (9,)


In [42]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate((a,b),axis=0))
print(np.stack([a,a,b],axis=0))
print(np.stack([a,a,b],axis=1))

[1 2 3 4 5 6]
[[1 2 3]
 [1 2 3]
 [4 5 6]]
[[1 1 4]
 [2 2 5]
 [3 3 6]]


In [6]:

a = np.array([0, 1, 2, 3, 4, 5])
# Reshape the array to 2 rows and 3 columns
print(a.reshape(2, 3).reshape(-2))


[0 1 2 3 4 5]


In [2]:
a = np.random.randint(0,100,size=(3,))
b = np.random.randint(0,100,size=(3,))
print(a,b)
# print(np.stack([a,a,b],axis = 1))
print(np.concatenate((a,b)))


[63 86 48] [14 79 56]
[63 86 48 14 79 56]
[86 86 86]
