## this is my first .ipynb

In [1]:
from turtledemo.penrose import start
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
a = np.array(1)
print(a, a.shape)

1 ()


In [29]:
a = np.array([1,2])
print(a, a.shape)

[1] (1,)


In [33]:
a = np.array([[1,2,3], [4,5,6]])
print(a, a.shape,a.dtype)

[[1 2 3]
 [4 5 6]] (2, 3) int64


# np.empty will generate random numbers just to fill the space

In [42]:
b = np.empty((3,4,4))
print(b, b.shape)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] (3, 4, 4)


# arange function used to create an 1D array with entries [s,e)

In [45]:
c = np.arange(5)
print(c, c.shape)

[0 1 2 3 4] (5,)


# use arange and reshape to form entries with entries 1 to 9

In [126]:
M = np.arange(0, 12).reshape(3, 4)
print(M, M.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


In [48]:
d = np.linspace(0,10,5)# END is included
g = np.linspace(0, 10, 5, dtype=int)
print(d, d.shape)
print(g, g.shape)

[0. 2. 4. 6. 8.] (5,)
[ 0.   2.5  5.   7.5 10. ] (5,)


In [49]:
f = np.logspace(0,6,3,base=2)# the number are the index of base
print(f, f.shape)

[ 1.  8. 64.] (3,)


# np.copy / copy.copy/ nparray.copy() creat deep copy

In [7]:
a = np.array([[1,2,3],[1,2,3]])
import copy
np_copy = np.copy(a); np_copy[0,0] = 999
copy_copy = copy.copy(a);copy_copy[0,0] = 999# python treat nparray as atomic object
nparray_copy = a.copy();nparray_copy[0,0] = 999
print(a)



[[1 2 3]
 [1 2 3]]


# Generate matrix whose main diagonal is 1

In [3]:
g = np.eye(3,4)
print(g, g.shape)
g = np.eye(4)
print(g, g.shape)# only one parameter in eye() to gen identity matrix

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]] (3, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)


# generate n*n matrix whose main diagonal is the number in the input list

In [54]:
h = np.diag([1,2,3,4,5.])
print(h, h.shape)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]] (5, 5)


# generate random numbers to fill the matrix between 0 - 1 dtype float

In [55]:
i = np.random.rand(3,2)
print(i, i.shape)

[[0.47324427 0.17583632]
 [0.22088977 0.57946166]
 [0.38249404 0.60883833]] (3, 2)


# generate random floats between specified range

In [57]:
j = np.random.uniform(3,7,size=(3,3))
print(j, j.shape)

[[3.97899417 3.84085483 6.25987096]
 [4.72697848 3.39403982 4.63388384]
 [3.95355518 5.82589282 5.22744648]] (3, 3)


# generate random int in specified range [a,b)#

In [122]:
k = np.random.randint(3,7,size=(3,3))
print(k, k.shape)

[[3 6 6]
 [6 3 5]
 [4 5 4]] (3, 3)


# generate floats based on normal distribution with mean and variance equal to 0 and 1

In [118]:
l = np.random.randn(3,3)
print(l, l.shape)

[[ 1.01050418 -0.27775188 -1.76484209]
 [-1.27507077 -1.22198204 -1.87963085]
 [-0.33998637 -0.12556068 -0.27696472]] (3, 3)


In [4]:
a = np.random.randint(0,100,size=(4,3))
print(a, a.shape)
print(a.dtype)

[[98 20 53]
 [86 97  0]
 [17 79 25]
 [98 96 96]] (4, 3)
int64


In [5]:
print(a[[1, 2], 1:])
print(a[:, 0][a[:, 0] > 27])

[[97  0]
 [79 25]]
[98 86 98]


In [6]:
print(a[1, (a[1] > 50) & (a[1] < 90)])
print(a[1] > 20)
print(a[::2])  # slicing is also supported in numpy

[86]
[ True  True False]
[[98 20 53]
 [17 79 25]]


In [131]:
a = np.arange(12).reshape(3,4)
print(a.transpose().tolist())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4)


# Broadcasting effect: When two axes are equal or one is 1, the dimension of size 1 is broadcast to the other.

In [133]:
a = np.arange(4, 7).reshape(3, 1)
b = np.arange(9, 9 + 2).reshape(1, 2)
print(a, b)
print(a + b)

[[4]
 [5]
 [6]] [[ 9 10]]
[[13 14]
 [14 15]
 [15 16]]


# multiplication of matrix

In [134]:
a = np.array([[1,2,3], [4,5,6]])
b = np.array([[15,6],[5,7],[2,5]])
print(a @ b)

[[31 35]
 [97 89]]


# Basic mathematics operatin

# square root

In [138]:
a = np.array([1,4,9,16])
print(np.sqrt(a))

[1. 2. 3. 4.]


# absolute value

In [140]:
a = np.arange(-9,-5).reshape(2,2)
print(np.abs(a))

[[9 8]
 [7 6]]


# trigonometric functions

In [141]:
print(np.sign(np.pi/2))

1.0


 # calculate the power

In [143]:
a = np.arange(8)
print(np.power(a,3))

[  0   1   8  27  64 125 216 343]


In [2]:
a = np.array([1])
print(a, a.shape)
b = np.array([[1,2,3], [4,5,6]])
print(a+b)

[1] (1,)
[[2 3 4]
 [5 6 7]]


In [6]:
print(int(0.9))

0


In [7]:
print(np.int64(0))

0


In [13]:
a = np.empty((3,3))
print(a,a.shape)
print(np.ones_like(a,dtype='bool'))

[[9.9e-324 2.0e-323 1.5e-323]
 [0.0e+000 9.9e-324 2.0e-323]
 [0.0e+000 9.9e-324 2.0e-323]] (3, 3)
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [16]:
a = np.random.randint(1,99,size=(4,4))
print(a)
print(a[0,1])

[[65 17 36 48]
 [53 90 38 59]
 [17 49 26 68]
 [83 84 76 43]]
17


# Rounding/Ceiling/Flooring

In [3]:
arr = np.array([1.2345, 2.3456, 3.4567])
print(np.round(arr,decimals=2))

[1.23 2.35 3.46]


In [5]:
arr = np.array([1.7345, 2.9456, 3.4567])
print(np.ceil(arr))

[2. 3. 4.]


In [6]:
arr = np.array([1.7345, 2.9456, 3.4567])
print(np.floor(arr))

[1. 2. 3.]


# Statistic

In [12]:
a = np.random.randint(0,100,size=(4,3))
print(np.sum(a))
print(np.median(a))
print(np.var(a))
print(np.std(a))

527
48.5
361.2430555555555
19.006395122577967


# np.max()/ np.min()/ np.median()

In [16]:
a = np.random.randint(1,16,size=(2,4,3))
print(a)

[[[ 9  6 12]
  [10  7  8]
  [ 8  6  5]
  [12  4  1]]

 [[11 10 13]
  [ 2 15  2]
  [ 6  6  1]
  [ 6  8 10]]]


In [18]:
print(np.mean(a,axis = 0))# like collapsing the specified axis
print(np.median(a,axis = 1))

[[10.   8.  12.5]
 [ 6.  11.   5. ]
 [ 7.   6.   3. ]
 [ 9.   6.   5.5]]
[[9.5 6.  6.5]
 [6.  9.  6. ]]


# np.max()/np.argmax()

In [24]:
a = np.random.randint(1,16,size=(9))
print(np.max(a),a)
print(np.argmax(a))

11 [10  2  5  9  7  5 11 11  4]
6
11


b# Percentile

In [17]:
a = np.array([1,33,56,99])
print(a)
print(np.percentile(a,50), np.mean(a))
# percentile focusing on the gap between each number
# first thing is to locate the gap in this case (4-1)*0.5 = 1.5 means it is in the second gap
# then use the second boundaries 33 + (56-33) * 0.5 ==

[ 1 33 56 99]
44.5 47.25
44.5


# Cumulative sum/product

In [14]:
a = np.arange(0,10).reshape(2,5)
print(a)
print(np.cumsum(a))
print(np.cumprod(a))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 0  1  3  6 10 15 21 28 36 45]
[0 0 0 0 0 0 0 0 0 0]


# Comparison

In [7]:
a = np.random.uniform(1,80,(3,2))
print(np.greater(a, 20))
print(np.less(a, 20))
print(np.equal(a,a))
# broadcasting effect

[[ True  True]
 [False False]
 [False  True]]
[[False False]
 [ True  True]
 [ True False]]
[[ True  True]
 [ True  True]
 [ True  True]]


# logic operator

In [17]:
print(np.logical_and(np.array([3,2]),[1,0]))
print(np.logical_not(np.array([3,2])))
print(np.logical_or(np.array([3,2]),[1,0]))
# all number except 0 represent true

[ True  True]
[False False]
[ True  True]


# where(condition, element/list if condition's satisfied, element/list if condition's not satisfied) function

In [22]:
a = np.arange(1,11)
success = np.ones((10,))
fail = np.zeros((1,10))
print(np.where(a > 3, success, fail))

[[0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]]


In [26]:
print(np.ones((1, 10)), '\n', np.ones((10,)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# select(list[condition],list[return result]) conditions and result align one by one

In [28]:
a = np.random.randint(0,101,size=(10,))
print(np.select([a>=85,(a<85) & (a>=75), a<75],['A range','B range','C range'],default='what the hell'))

['A range' 'C range' 'C range' 'B range' 'C range' 'C range' 'B range'
 'C range' 'C range' 'A range']


# np.sort() & arr.sort()

In [35]:
a = np.random.randint(1,100,size=(4,4))
print(a)
print()
print(np.sort(a))
print()
a.sort()
print(a)# regular sort only sort

[[56 22 45 48]
 [26 62 70 97]
 [19 46 91 82]
 [28 63 23  6]]

[[22 45 48 56]
 [26 62 70 97]
 [19 46 82 91]
 [ 6 23 28 63]]

[[22 45 48 56]
 [26 62 70 97]
 [19 46 82 91]
 [ 6 23 28 63]]


# expand_dims(nparray, axis)

In [9]:
a = np.arange(10).reshape(2, 5)
print(a, a.shape, a.ndim)
print('-----------------------')
for _ in range(a.ndim + 1):
    b = np.expand_dims(a, axis=_)
    print(b, b.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5) 2
-----------------------
[[[0 1 2 3 4]
  [5 6 7 8 9]]] (1, 2, 5)
[[[0 1 2 3 4]]

 [[5 6 7 8 9]]] (2, 1, 5)
[[[0]
  [1]
  [2]
  [3]
  [4]]

 [[5]
  [6]
  [7]
  [8]
  [9]]] (2, 5, 1)


In [2]:
# remove duplicate element
a = np.random.randint(1,3,(4,4))
print(a)
print(np.unique(a))

[[2 2 1 2]
 [2 1 1 2]
 [2 2 1 1]
 [1 1 2 2]]
[1 2]


# np.concatenate() #two nparray should be the same in shape

In [10]:
a= np.array([[1,2,3],[99,100,101]])
b = np.array([[4,5,6],[1,3,6]])
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[  1   2   3]
 [ 99 100 101]
 [  4   5   6]
 [  1   3   6]]
[[  1   2   3   4   5   6]
 [ 99 100 101   1   3   6]]


# np.split(nparray, number of nparrays after splitting)

In [9]:
a = np.arange(10)
b = np.split(a, 5)
print(b, type(b))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])] <class 'list'>


[[76  9 64]
 [65 34 95]
 [38 21 78]]
[[34 95]]
